name: CI macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow manual triggering

jobs:
  macos-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ macos-11, macos-12 ]
    steps:
      - uses: actions/checkout@v3
      - name: Install sage
        # run: brew install --build-from-source --force ./sage.rb
        run: brew install --cask sage
      - name: Compile code
        run: sage setup.py develop
      - name: Run unit tests
        working-directory: ./unit_tests
        run: sage unit_tests.sage
