name: CI ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allow manual triggering

jobs:
  ubuntu-CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Install sage
        run: sudo apt install sagemath
      - name: Compile code
        run: sudo sage setup.py develop
      - name: Run unit tests
        working-directory: ./unit_tests
        run: sage unit_tests.sage
